"""Git-based publish pipeline for generated skills.

Handles staging, committing, and pushing SKILL.md files to the
upstream Git repository that serves as the system of record.
"""

from __future__ import annotations

import logging
import subprocess
from dataclasses import dataclass
from pathlib import Path

from skill_builder.configuration import Configuration

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class PublishResult:
    commit_sha: str
    commit_message: str
    pushed: bool
    file_path: str


class GitPublisher:
    """Commits and pushes new skills to the Git repository."""

    def __init__(self, config: Configuration) -> None:
        self._repo_dir = Path(config.git_repo_dir).resolve()
        self._remote = config.git_remote
        self._branch = config.git_branch
        self._push_enabled = config.git_push_enabled
        self._author_name = config.git_author_name
        self._author_email = config.git_author_email

    def _run(self, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["git", *args],
            cwd=self._repo_dir,
            capture_output=True,
            text=True,
            check=check,
        )

    def is_available(self) -> bool:
        """Check if the repo dir is a valid git repository."""
        try:
            result = self._run("rev-parse", "--is-inside-work-tree", check=False)
            return result.returncode == 0 and result.stdout.strip() == "true"
        except FileNotFoundError:
            return False

    def publish(
        self,
        skill_file: Path,
        marketplace_file: Path | None,
        plugin: str,
        skill_name: str,
    ) -> PublishResult:
        """Stage, commit, and optionally push a new skill.

        Args:
            skill_file: Absolute path to the new SKILL.md.
            marketplace_file: Absolute path to marketplace.json (if updated).
            plugin: Plugin category name.
            skill_name: Skill identifier.

        Returns:
            PublishResult with commit details.
        """
        rel_skill = skill_file.relative_to(self._repo_dir)

        files_to_stage = [str(rel_skill)]
        if marketplace_file and marketplace_file.exists():
            rel_mp = marketplace_file.relative_to(self._repo_dir)
            files_to_stage.append(str(rel_mp))

        for f in files_to_stage:
            self._run("add", f)

        commit_msg = f"feat(registry): add {plugin}/{skill_name}\n\nGenerated by Skill Builder agent pipeline."

        self._run(
            "commit",
            "-m", commit_msg,
            f"--author={self._author_name} <{self._author_email}>",
        )

        sha = self._run("rev-parse", "HEAD").stdout.strip()[:12]

        pushed = False
        if self._push_enabled:
            try:
                self._run("push", self._remote, self._branch)
                pushed = True
                logger.info("Pushed commit %s to %s/%s", sha, self._remote, self._branch)
            except subprocess.CalledProcessError as exc:
                logger.warning(
                    "Git push failed (commit %s saved locally): %s",
                    sha, exc.stderr.strip(),
                )

        return PublishResult(
            commit_sha=sha,
            commit_message=commit_msg,
            pushed=pushed,
            file_path=str(rel_skill),
        )
